---
# Builds, tests and publishes the output to the Play store internal track.
name: Build & Espresso Test

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: android-test-coverage-sample-runners
    steps:
      - uses: actions/checkout@v4
      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            assembleDebug
            assembleRelease
            assembleAndroidTest
            assembleReleaseUnitTest
            :app:compileReleaseSources
            :app:packageReleaseBundle
            lint
            app:createDebugUnitTestCoverageReport
            :app:assembleDebugAndroidTest --scan --stacktrace
        timeout-minutes: 10

      - name: Unit JUnit Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "**/build/test-results/test*UnitTest/TEST-*.xml"

      - run: |
          find -name report.xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./app/build/reports/coverage/test/debug/report.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true

      - name: Upload lint result artifact
        uses: actions/upload-artifact@v3
        with:
          name: lint report
          path: app/build/reports/lint-results-debug.html
        if: always()

  espresso-test:
    name: "Espresso test"
    runs-on: android-test-coverage-sample-runners
    needs: build
    strategy:
      fail-fast: false
      matrix:
        android-api: [ 33,32,31,30 ]
    steps:
      - run: echo "/android-sdk/platform-tools/" >> $GITHUB_PATH
      - uses: actions/checkout@v4
      - name: "Check snapshot exists"
        id: check_snapshot_exists
        uses: andstor/file-existence-action@v2
        with:
          files: "/android-sdk/user_home/avd/test-${{ matrix.android-api }}.avd/snapshots/default_boot/screenshot.png"

      - name: Create AVD and generate snapshot for caching
        if: steps.check_snapshot_exists.outputs.files_exists == 'false'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.android-api }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -camera-front none
          profile: pixel_3a
          target: google_apis
          ram-size: 6000M
          avd-name: test-${{ matrix.android-api }}
          disable-animations: true
          arch: x86_64
          cores: 2
          sdcard-path-or-size: 1000M
          script: |
            echo "Created AVD snapshot"

      - name: Espresso Test
        uses: reactivecircus/android-emulator-runner@v2
        timeout-minutes: 20
        with:
          api-level: ${{ matrix.android-api }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -camera-front none
          profile: pixel_3a
          target: google_apis
          ram-size: 6000M
          avd-name: test-${{ matrix.android-api }}
          disable-animations: true
          arch: x86_64
          cores: 2
          sdcard-path-or-size: 1000M
          script: |
            adb shell settings put global bluetooth_on 0
            adb shell rm -rf /sdcard/googletest || echo "Couldn't delete googletest folder"
            adb uninstall com.example.testcoveragesample || echo "com.example.testcoveragesample not installed"
            adb uninstall com.example.testcoveragesample.test || echo "com.example.testcoveragesample.test not installed"
            adb logcat -c
            adb logcat > emulator.log & echo $! > logcat_file.pid
            adb logcat "*:S MonitoringInstr:V AndroidJUnitRunner:V TestRequestBuilder:V TestExecutor:V TestRunner:V" --format=color & echo $! > logcat_console.pid
            echo 0 > gradle.exit # Set a default exit code.
            ./gradlew createDebugCoverageReport --max-workers=1 --stacktrace --scan || echo $? > gradle.exit
            # Stop capturing logcat output.
            kill $(cat logcat_file.pid)    || echo "::warning file=.github/workflows/ci.yml::Logcat process $(cat logcat_file.pid) didn't exist."
            kill $(cat logcat_console.pid) || echo "::warning file=.github/workflows/ci.yml::Logcat process $(cat logcat_console.pid) didn't exist."
            adb logcat -d --buffer=crash --format=color
            exit $(cat gradle.exit)

      - name: Upload logcat
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logcat-${{ matrix.android-api }}-${{ matrix.flavour }}
          path: |
            ${{ github.workspace }}/emulator.log
            ${{ github.workspace }}/emulator-startup.log

      - name: Upload connected test result artifact
        uses: actions/upload-artifact@v3
        with:
          name: espresso-test-reports-${{ matrix.android-api }}
          path: app/build/reports/androidTests/connected/
        if: always()

      - name: Espresso JUnit Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: app/build/outputs/androidTest-results/connected/*.xml
      - name: Upload connected test coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: espresso-test-coverage-${{ matrix.android-api }}
          path: app/build/reports/coverage/androidTest/debug/
        if: always()
      - name: Upload coverage
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') }}
        uses: codecov/codecov-action@v3
        with:
          files: app/build/reports/coverage/androidTest/debug/connected/report.xml
          flags: espressotests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true
