---
# Builds, tests and publishes the output to the Play store internal track.
name: Build & Espresso Test

"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Gradle build
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa # v2
        with:
          dependency-graph: generate-and-submit
          arguments: |
            assembleDebug
            assembleRelease
            lint
            app:createDebugUnitTestCoverageReport --scan --stacktrace
        timeout-minutes: 10

      - name: Unit JUnit Report
        uses: mikepenz/action-junit-report@b1b7f659602565970688b2e2588738b9398e895d # v4
        if: always()
        with:
          report_paths: "**/TEST-*.xml"
          detailed_summary: true
          include_passed: true

      - name: Upload coverage
        if: ${{ (github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)) }}
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
        with:
          files: ./app/build/reports/coverage/test/debug/report.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true

      - name: Upload lint result artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4
        with:
          name: lint report
          path: app/build/reports/lint-results-debug.html
        if: always()

  espresso-test:
    name: "Espresso test"
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        android-api: [34, 24, 21]
    steps:
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Gradle build
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa # v2
        with:
          arguments: |
            :app:packageDebugAndroidTest :app:packageDebug :app:compileDebugAndroidTestKotlin :app:compileDebugAndroidTestJavaWithJavac --daemon --scan
          dependency-graph: generate
        timeout-minutes: 10

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.android-api }}

      - name: Create AVD and generate snapshot for caching
        uses: reactivecircus/android-emulator-runner@eaf4c246b5ce90db0e68560f6443978a636797aa # v2
        if: steps.avd-cache.outputs.cache-hit != 'true'
        with:
          api-level: ${{ matrix.android-api }}
          force-avd-creation: false
          emulator-options: -no-window -gpu auto -noaudio -no-boot-anim -camera-back none -camera-front none
          profile: pixel_3a
          target: google_apis
          ram-size: 4000M
          avd-name: test-${{ matrix.android-api }}
          disable-animations: true
          arch: x86_64
          cores: 1
          sdcard-path-or-size: 1000M
          script: |
            echo "Created AVD snapshot"

      - name: Espresso Test
        uses: reactivecircus/android-emulator-runner@eaf4c246b5ce90db0e68560f6443978a636797aa # v2
        timeout-minutes: 20
        with:
          api-level: ${{ matrix.android-api }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu auto -noaudio -no-boot-anim -camera-back none -camera-front none
          profile: pixel_3a
          target: google_apis
          ram-size: 4000M
          avd-name: test-${{ matrix.android-api }}
          disable-animations: true
          arch: x86_64
          cores: 1
          sdcard-path-or-size: 1000M
          script: |
            adb shell settings put global bluetooth_on 0
            adb shell rm -rf /sdcard/googletest || echo "Couldn't delete googletest folder"
            adb uninstall com.example.testcoveragesample || echo "com.example.testcoveragesample not installed"
            adb uninstall com.example.testcoveragesample.test || echo "com.example.testcoveragesample.test not installed"
            ./gradlew createDebugCoverageReport --max-workers=1 --stacktrace --scan --daemon --info

      - name: Upload connected test result artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4
        with:
          name: espresso-test-reports-${{ matrix.android-api }}
          path: app/build/reports/androidTests/connected/
        if: always()

      - name: Espresso JUnit Report
        uses: mikepenz/action-junit-report@b1b7f659602565970688b2e2588738b9398e895d # v4
        if: always()
        with:
          report_paths: "**/TEST-*.xml"
          detailed_summary: true
          include_passed: true

      - name: Upload connected test coverage artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4
        with:
          name: espresso-test-coverage-${{ matrix.android-api }}
          path: app/build/reports/coverage/androidTest/debug/
        if: always()
      - name: Upload coverage
        if: ${{ (github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)) }}
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
        with:
          files: app/build/reports/coverage/androidTest/debug/connected/report.xml
          flags: espressotests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true
