#growse:$2y$05$8RDudDIlFqryyuakx/GMBuJsTmVJUDvb2rJXKMZQ/Pm75XFxkHZGG
---
# Builds, tests and publishes the output to the Play store internal track.
name: Build & Espresso Test

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
      - name: Assemble
        run: ./gradlew assembleDebug assembleAndroidTest --no-daemon --scan
        timeout-minutes: 10

  espresso-test:
    name: "Espresso test"
    runs-on: self-hosted
    needs: build
    services:
      emulator:
        image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2
        ports:
          - 8554:8554
          - 5555:5555
    strategy:
      matrix:
        android-api: [33]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
      - name: adb connect
        run: adb connect localhost:5555
        timeout-minutes: 1
      - name: Espresso test
        run: ./gradlew createDebugCoverageReport --no-daemon --scan
        timeout-minutes: 10
      # - name: Espresso Test
      #   uses: reactivecircus/android-emulator-runner@v2
      #   timeout-minutes: 20
      #   with:
      #     api-level: ${{ matrix.android-api }}
      #     script: |
      #       ./gradlew createDebugCoverageReport --no-daemon --scan
      #     profile: pixel_3a
      #     target: google_apis
      #     disable-animations: true
      #     arch: x86_64
      #     sdcard-path-or-size: 1000M
      - name: Upload connected test result artifact
        uses: actions/upload-artifact@v3
        with:
          name: espresso-test-reports-${{ matrix.android-api }}
          path: app/build/reports/androidTests/connected/
        if: always()
      - name: Upload connected test XML
        uses: actions/upload-artifact@v3
        with:
          name: espresso-test-xml-${{ matrix.android-api }}
          path: app/build/outputs/androidTest-results/connected/*.xml
      - name: Upload connected test coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: espresso-test-coverage-${{ matrix.android-api }}
          path: app/build/reports/coverage/androidTest/debug/
        if: always()
